nomeFunc = input("Digite seu nome, funcionário: ")
sal = float(input("Qual é o seu salário atual? "))
aumento = float(input("Em qual porcentagem seu salário foi aumentado? "))
novoSal = sal+(sal*(aumento/100))
print("O novo salário de", nomeFunc, "é", novoSal, "reais, com aumento de", aumento, "por cento.")